'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@supabase/supabase-js';
import { defaultContent, Content } from '@/lib/default-content';

const sections=['Site','Profile','About','Hobbies','Habits','Projects','Services','Staffing','Cards','Connections','Theme','Advanced JSON'];
const supabase=process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY):null;

export default function Admin(){
 const [content,setContent]=useState<Content>(defaultContent); const [active,setActive]=useState('Site'); const [status,setStatus]=useState(''); const [raw,setRaw]=useState(''); const [checking,setChecking]=useState(true);
 useEffect(()=>{(async()=>{if(supabase){const {data:session}=await supabase.auth.getSession();if(!session.session){window.location.href='/admin/login';return;}const {data}=await supabase.from('site_content').select('content').eq('id','main').maybeSingle();if(data?.content)setContent({...defaultContent,...data.content});}setChecking(false);})()},[]);
 function set(path:string,value:any){setContent(prev=>{const next=structuredClone(prev) as any;const parts=path.split('.');let o=next;for(let i=0;i<parts.length-1;i++)o=o[parts[i]];o[parts.at(-1)!]=value;return next;});}
 function arr(path:string){return path.split('.').reduce((o:any,k)=>o?.[k],content) || [];}
 function editArray(path:string,index:number,value:string){const a=[...arr(path)];a[index]=value;set(path,a)}
 function addArray(path:string){set(path,[...arr(path),'New item'])}
 function removeArray(path:string,index:number){const a=arr(path).filter((_:any,i:number)=>i!==index);set(path,a)}
 async function save(){setStatus('Saving...');if(!supabase){localStorage.setItem('livingyuji-content',JSON.stringify(content));setStatus('Saved locally. Configure Supabase for shared production data.');return;}const {error}=await supabase.from('site_content').upsert({id:'main',content,updated_at:new Date().toISOString()});setStatus(error?error.message:'Published successfully.');}
 function loadRaw(){setRaw(JSON.stringify(content,null,2));}
 function applyRaw(){try{const parsed=JSON.parse(raw);setContent(parsed);setStatus('JSON loaded into editor. Click Publish.')}catch{setStatus('Invalid JSON.');}}
 if(checking) return <main className="admin-shell"><div className="login"><div className="login-box">Checking admin session...</div></div></main>;
 return <main className="admin-shell"><header className="admin-nav"><div className="admin-brand">LIVINGYUJI / ADMIN</div><div style={{display:'flex',gap:10}}><a className="admin-btn" href="/">VIEW SITE</a><button className="admin-btn primary" onClick={save}>PUBLISH</button></div></header><div className="admin-layout"><aside className="admin-side">{sections.map(s=><button className={active===s?'active':''} onClick={()=>{setActive(s);if(s==='Advanced JSON')loadRaw()}} key={s}>{s}</button>)}</aside><section className="admin-main"><div className="notice">Every public-facing value in this build is driven by this content model. Use the sections below for normal editing, or <b>Advanced JSON</b> for complete control.</div>{status&&<div className="notice">{status}</div>}{active==='Site'&&<Site c={content} set={set}/>} {active==='Profile'&&<Profile c={content} set={set} editArray={editArray} addArray={addArray} removeArray={removeArray}/>} {active==='About'&&<About c={content} set={set}/>} {['Hobbies','Habits'].includes(active)&&<SimpleArray title={active} path={active.toLowerCase()} items={arr(active.toLowerCase())} editArray={editArray} addArray={addArray} removeArray={removeArray}/>} {active==='Projects'&&<ProjectEditor c={content} set={set}/>} {active==='Services'&&<ProjectEditor c={content} set={set} services/>} {active==='Staffing'&&<SimpleArray title="Staffing" path="staffing" items={content.staffing} editArray={editArray} addArray={addArray} removeArray={removeArray}/>} {active==='Cards'&&<SimpleArray title="Cards" path="cards" items={content.cards} editArray={editArray} addArray={addArray} removeArray={removeArray}/>} {active==='Connections'&&<Connections c={content} set={set}/>} {active==='Theme'&&<Theme c={content} set={set}/>} {active==='Advanced JSON'&&<div className="admin-card"><h2>FULL CONTENT JSON</h2><p style={{color:'#aaa4b4'}}>This is the escape hatch: anything in the public content model can be changed here.</p><textarea className="json-editor" value={raw} onChange={e=>setRaw(e.target.value)}/><div className="admin-actions"><button className="admin-btn" onClick={loadRaw}>RELOAD FROM CURRENT STATE</button><button className="admin-btn primary" onClick={applyRaw}>APPLY JSON</button><button className="admin-btn" onClick={()=>{setRaw(JSON.stringify(defaultContent,null,2));}}>LOAD DEFAULTS</button></div></div>}</section></div></main>
}
function Field({label,value,onChange,area=false}:{label:string;value:any;onChange:(v:string)=>void;area?:boolean}){return <div className="field"><label>{label}</label>{area?<textarea value={value??''} onChange={e=>onChange(e.target.value)}/>:<input value={value??''} onChange={e=>onChange(e.target.value)}/>}</div>}
function Site({c,set}:{c:Content;set:(p:string,v:any)=>void}){return <div className="admin-card"><h2>GLOBAL SITE</h2><Field label="Brand" value={c.site.brand} onChange={v=>set('site.brand',v)}/><Field label="Browser title" value={c.site.title} onChange={v=>set('site.title',v)}/><Field label="Hero kicker" value={c.site.kicker} onChange={v=>set('site.kicker',v)}/><Field label="Hero title" value={c.site.heroTitle} onChange={v=>set('site.heroTitle',v)}/><Field label="Hero description" value={c.site.heroText} onChange={v=>set('site.heroText',v)} area/><Field label="Dashboard button" value={c.site.dashboardLabel} onChange={v=>set('site.dashboardLabel',v)}/><Field label="Footer" value={c.site.footer} onChange={v=>set('site.footer',v)}/><h2 style={{marginTop:35}}>NAVIGATION</h2>{c.nav.map((n,i)=><div key={i} className="field"><label>Item {i+1}</label><input value={`${n.label} | ${n.href}`} onChange={e=>{const [label,...rest]=e.target.value.split('|');const nav=[...c.nav];nav[i]={label:label.trim(),href:rest.join('|').trim()};set('nav',nav)}}/></div>)}</div>}
function Profile({c,set,editArray,addArray,removeArray}:{c:Content;set:any;editArray:any;addArray:any;removeArray:any}){return <div className="admin-card"><h2>PROFILE</h2><Field label="Profile image URL" value={c.profile.image} onChange={v=>set('profile.image',v)}/><Field label="Name" value={c.profile.name} onChange={v=>set('profile.name',v)}/><Field label="Age" value={c.profile.age} onChange={v=>set('profile.age',v)}/><Field label="Place" value={c.profile.place} onChange={v=>set('profile.place',v)}/><Field label="Class / Grade" value={c.profile.classGrade} onChange={v=>set('profile.classGrade',v)}/><Field label="Role" value={c.profile.role} onChange={v=>set('profile.role',v)}/><ArrayEditor title="Goals" path="profile.goals" items={c.profile.goals} editArray={editArray} addArray={addArray} removeArray={removeArray}/><ArrayEditor title="Why" path="profile.why" items={c.profile.why} editArray={editArray} addArray={addArray} removeArray={removeArray}/></div>}
function About({c,set}:{c:Content;set:any}){return <div className="admin-card"><h2>ABOUT + STATS</h2><Field label="Section title" value={c.about.title} onChange={v=>set('about.title',v)}/><Field label="Subtitle" value={c.about.subtitle} onChange={v=>set('about.subtitle',v)}/>{c.about.paragraphs.map((p,i)=><Field key={i} label={`Paragraph ${i+1}`} value={p} onChange={v=>{const a=[...c.about.paragraphs];a[i]=v;set('about.paragraphs',a)}} area/>)}<h2 style={{marginTop:30}}>Stats</h2>{c.about.stats.map((s,i)=><div key={i} className="field"><label>Stat {i+1}</label><input value={`${s.label} | ${s.value}`} onChange={e=>{const [label,...rest]=e.target.value.split('|');const a=[...c.about.stats];a[i]={label:label.trim(),value:rest.join('|').trim()};set('about.stats',a)}}/></div>)}</div>}
function ArrayEditor({title,path,items,editArray,addArray,removeArray}:{title:string;path:string;items:string[];editArray:any;addArray:any;removeArray:any}){return <div><h2 style={{marginTop:30}}>{title}</h2>{items.map((x,i)=><div key={i} style={{display:'flex',gap:8,margin:'8px 0'}}><input style={{flex:1,background:'#17151e',border:'1px solid #4b4357',color:'#fff',padding:11}} value={x} onChange={e=>editArray(path,i,e.target.value)}/><button className="admin-btn danger" onClick={()=>removeArray(path,i)}>×</button></div>)}<button className="admin-btn" onClick={()=>addArray(path)}>+ ADD</button></div>}
function SimpleArray({title,path,items,editArray,addArray,removeArray}:any){return <div className="admin-card"><h2>{title.toUpperCase()}</h2><ArrayEditor title="Items" path={path} items={items} editArray={editArray} addArray={addArray} removeArray={removeArray}/></div>}
function ProjectEditor({c,set,services=false}:{c:Content;set:any;services?:boolean}){const path=services?'plugins':'projects';const items:any[]=c[path];function update(i:number,k:string,v:any){const a=[...items];a[i]={...a[i],[k]:v};set(path,a)}function add(){set(path,[...items,{id:`new-${Date.now()}`,name:'NEW PROJECT',description:'Describe it here.',tags:['Web'],url:'#'}])}function remove(i:number){set(path,items.filter((_,x)=>x!==i))}return <div className="admin-card"><h2>{services?'SERVICES':'PROJECTS'}</h2>{items.map((p,i)=><div key={p.id} className="admin-card" style={{background:'#191720'}}><Field label="Name" value={p.name} onChange={v=>update(i,'name',v)}/><Field label="Description" value={p.description} onChange={v=>update(i,'description',v)} area/><Field label="Tags (comma separated)" value={p.tags.join(', ')} onChange={v=>update(i,'tags',v.split(',').map((x:string)=>x.trim()).filter(Boolean))}/><Field label="URL" value={p.url} onChange={v=>update(i,'url',v)}/><div className="admin-actions"><button className="admin-btn danger" onClick={()=>remove(i)}>DELETE</button></div></div>)}<button className="admin-btn primary" onClick={add}>+ ADD {services?'SERVICE':'PROJECT'}</button></div>}
function Connections({c,set}:{c:Content;set:any}){function update(i:number,k:string,v:string){const a=[...c.connections];a[i]={...a[i],[k]:v};set('connections',a)}return <div className="admin-card"><h2>CONNECTIONS</h2>{c.connections.map((x,i)=><div className="admin-card" key={i}><Field label="Name" value={x.name} onChange={v=>update(i,'name',v)}/><Field label="Handle" value={x.handle} onChange={v=>update(i,'handle',v)}/><Field label="URL" value={x.url} onChange={v=>update(i,'url',v)}/></div>)}</div>}
function Theme({c,set}:{c:Content;set:any}){return <div className="admin-card"><h2>THEME</h2>{Object.entries(c.theme).map(([k,v])=><Field key={k} label={k} value={v} onChange={x=>set(`theme.${k}`,x)}/>)}</div>}
